### ISSUE TITLE
SearchIndex pipeline fails on ubuntu in Github Actions

### ISSUE THREAD

**Issue by alanta** [alanta/Memoirs-Theme#2]
```
[DBUG] Exception while executing pipeline SearchIndex/PostProcess: System.Collections.Generic.KeyNotFoundException: The given key 'title' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Lunr.Builder.CalculateAverageFieldLengths()
   at Lunr.Builder.Build()
   at Lunr.Index.Build(Func`2 config, TrimmerBase trimmer, StopWordFilterBase stopWordFilter, StemmerBase stemmer, Tokenizer tokenizer, PipelineFunctionRegistry registry, IEnumerable`1 indexingPipeline, IEnumerable`1 searchPipeline, Field[] fields)
   at MemoirsTheme.Modules.LunrIndexer.ExecuteContextAsync(IExecutionContext context) in /home/runner/work/Memoirs-Theme/Memoirs-Theme/Modules/LunrIndexer.cs:line 20
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Core.Engine.ExecuteModulesAsync(ExecutionContextData contextData, IExecutionContext parent, IEnumerable`1 modules, ImmutableArray`1 inputs, ILogger logger)```

**Comment by alanta** [comment]
Fixed : was a case sensitivity thing after all (Linux vs Windows)
